### ISSUE TITLE
[Bug]: Error using ListReport Extension

### ISSUE THREAD

**Issue by leaguiar85** [spreadsheetimporter/ui5-cc-spreadsheetimporter#510]
### OData Version

OData V2

### Draft

Yes

### Scenario

List Report like SM30

### Environment

VSCode preview ok / Error in On Premisse

### UI5 Spreadsheet Component

v_0_33_0

### What happened?

I´m trying to use it in an extension button in List Report.
![image](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/54242167/91a5a4b3-a74f-4ce6-a68a-9a853d4d47a5)

Testing locally on VSCode works fine. But when I deploy and try to test in Launchpad, it cannot find the component usage in the manifest.
![image](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/54242167/371f2a3b-6501-4379-bccb-5c831531a71b)

I've checked the version, and everything is fine.
![image](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/54242167/c7939556-a19e-4bd2-bb23-e91de198182b)

![image](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/54242167/084a8e50-333d-4d81-a1b1-de32da9b7972)

In the attachment, are my manifest and controller.
[manifest.json](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/files/14462803/manifest.json)
[ListReportExt.controller.txt](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/files/14462804/ListReportExt.controller.txt)

PS: This point works fine in the preview application(VSCode), but not work after deployment in the launchpad
![image](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/54242167/34fce9de-653b-431c-b815-0f66a7660941)

Could you please help me to find out what I´m doing wrong?

Thanks in advance
Leandro

### Relevant log output

```shell
Device-dbg.js:85 2024-03-01 12:26:47 Device API logging initialized - DEVICE
VM54913:1 Uncaught ReferenceError: uim_main is not defined
    at onload (VM54913:1:1)
Log-dbg.js:452 2024-03-01 12:26:55.346500 App  has errors and may not run correctly; see SAP Note 2364579 -  zehsam_cfgemp
g @ Log-dbg.js:452
Log-dbg.js:452 2024-03-01 12:26:55.346699 Error in app component zehsam_cfgemp: No descriptor was found -  zehsam_cfgemp
g @ Log-dbg.js:452
Log-dbg.js:452 2024-03-01 12:26:56.693500 Deprecated API call of 'sap.ushell.Container.getService'. Please use 'getServiceAsync' instead -  sap.ushell.services.Container
g @ Log-dbg.js:452
common.load.xhrlogon-dbg.js:3066 
        
        
       Failed to load resource: the server responded with a status of 404 ()
a.send @ common.load.xhrlogon-dbg.js:3066
common.load.xhrlogon-dbg.js:3066 
        
        
       Failed to load resource: the server responded with a status of 404 ()
a.send @ common.load.xhrlogon-dbg.js:3066
common.load.xhrlogon-dbg.js:3066 
        
        
       Failed to load resource: the server responded with a status of 404 ()
a.send @ common.load.xhrlogon-dbg.js:3066
:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/configemployeekpi/zehsamcfgemp/annotations/annotation.xml?sap-language=EN&sap-client=010:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
assert-dbg.js:33 Falha na declaração: Source must contain an annotation object to be merged
n @ assert-dbg.js:33
Log-dbg.js:452 2024-03-01 12:27:05.391899 Deprecated API call of 'sap.ushell.CrossApplicationNavigation.createEmptyAppState'. Please use 'createEmptyAppStateAsync' instead -  sap.ushell.services.CrossApplicationNavigation
g @ Log-dbg.js:452
Log-dbg.js:452 2024-03-01 12:27:05.399000 Deprecated API call of 'sap.ushell.CrossApplicationNavigation.isInitialNavigation'. Please use 'isInitialNavigationAsync' instead -  sap.ushell.services.CrossApplicationNavigation
g @ Log-dbg.js:452
Log-dbg.js:453 2024-03-01 12:27:07.601500 No valid cache key segment last modification date provided by OData annotations -  FioriElements: genericUtilities.CacheHelper
g @ Log-dbg.js:453
Log-dbg.js:452 2024-03-01 12:27:33.502899 Deprecated API call of 'sap.ushell.CrossApplicationNavigation.createEmptyAppState'. Please use 'createEmptyAppStateAsync' instead -  sap.ushell.services.CrossApplicationNavigation
g @ Log-dbg.js:452
Log-dbg.js:452 2024-03-01 12:27:33.894899 Deprecated API call of 'sap.ushell.CrossApplicationNavigation.createEmptyAppState'. Please use 'createEmptyAppStateAsync' instead -  sap.ushell.services.CrossApplicationNavigation
g @ Log-dbg.js:452
assert-dbg.js:33 Falha na declaração: sName must be a string or omitted
n @ assert-dbg.js:33
Log-dbg.js:453 2024-03-01 12:27:35.311399 No valid cache key segment last modification date provided by OData annotations -  FioriElements: genericUtilities.CacheHelper
g @ Log-dbg.js:453
assert-dbg.js:33 Falha na declaração: could not find any translatable text for key 'searchButtonStatus_undefined' in bundle file(s): '/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/esh/search/ui/resources/resources_en.properties', '/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/esh/search/ui/resources/resources.properties'
n @ assert-dbg.js:33
assert-dbg.js:33 Falha na declaração: could not find any translatable text for key 'searchButtonStatus_undefined' in bundle file(s): '/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/esh/search/ui/resources/resources_en.properties', '/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/esh/search/ui/resources/resources.properties'
n @ assert-dbg.js:33
Log-dbg.js:452 2024-03-01 12:27:45.344399 FLP PageBuildingAdapter: remote catalog service sap/ushell_abap/pbServices/ui2/RemoteCatalogService must be loaded before use. -  
g @ Log-dbg.js:452
:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/configemployeekpi/zehsamcfgemp/thirdparty/customControl/spreadsheetImporter/v0_33_0/manifest.json?sap-language=EN&sap-client=010:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
Component-preload.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
Component-preload.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
Log-dbg.js:452 2024-03-01 12:28:56.577000 failed to load JavaScript resource: cc/spreadsheetimporter/v0_33_0/Component-preload.js -  sap.ui.ModuleSystem
g @ Log-dbg.js:452
common.load.xhrlogon-dbg.js:3066 
        
        
       Failed to load resource: the server responded with a status of 404 ()
a.send @ common.load.xhrlogon-dbg.js:3066
:44300/sap/bc/ui2/fl…RJYNARUF6E9OZQ3EY:1 Uncaught (in promise) ModuleError: failed to load 'cc/spreadsheetimporter/v0_33_0/Component.js' from ../ui5_ui5/ui2/ushell/resources/~20221102093300~/configemployeekpi/zehsamcfgemp/thirdparty/customControl/spreadsheetImporter/v0_33_0/Component.js: 404
    at se (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:7148)
    at ne.failWith (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:4989)
    at me (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:13743)
    at be (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:15705)
    at Object.r [as require] (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:19045)
    at https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/core-min-1.js:460:34708
    at new Promise (<anonymous>)
    at https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/core-min-1.js:460:34675
Caused by: XHRLoadError: 404
    at n (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:9771)
    at XMLHttpRequest.<anonymous> (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:10023)
    at a (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:327:5568)
    at r.dispatch (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:327:6311)
    at a.handleEvent (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:327:36567)
    at XMLHttpRequest.t [as _fnHandler] (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:327:36898)
    at a.send (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:327:39186)
    at window.XMLHttpRequest.<computed> [as send] (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:263:318)
    at pe (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:10115)
    at me (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:13719)
ListReportExt-dbg.controller.js:104 Uncaught (in promise) ModuleError: failed to load 'cc/spreadsheetimporter/v0_33_0/Component.js' from ../ui5_ui5/ui2/ushell/resources/~20221102093300~/configemployeekpi/zehsamcfgemp/thirdparty/customControl/spreadsheetImporter/v0_33_0/Component.js: 404
    at se (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:7148)
    at ne.failWith (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:4989)
    at me (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:13743)
    at be (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:15705)
    at Object.r [as require] (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:19045)
    at https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/core-min-1.js:460:34708
    at new Promise (<anonymous>)
    at https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/core-min-1.js:460:34675
Caused by: XHRLoadError: 404
    at n (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:9771)
    at XMLHttpRequest.<anonymous> (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:10023)
    at a (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:327:5568)
    at r.dispatch (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:327:6311)
    at a.handleEvent (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:327:36567)
    at XMLHttpRequest.t [as _fnHandler] (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:327:36898)
    at a.send (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:327:39186)
    at window.XMLHttpRequest.<computed> [as send] (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:263:318)
    at pe (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:10115)
    at me (https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20221102093300~/sap/ushell_abap/bootstrap/evo/abap.js:9:13719)
```

### Spreadsheet Component Init

```js
sap.ui.define([
    "sap/m/MessageToast"
], function (MessageToast) {
    'use strict';

    return {
        openSpreadsheetUploadDialog: async function (oEvent) {
            debugger;
            this.getView().setBusyIndicatorDelay(0);
            this.getView().setBusy(true);
            //if (!this.spreadsheetUpload) {
            this.spreadsheetUpload = await this.getView()
                .getController()
                .getOwnerComponent()
                .createComponent({
                    usage: "spreadsheetImporter",
                    async: true,
                    componentData: {
                        context: this,
                        standalone: false,
                        createActiveEntity: false,
                        activateDraft: false,
                        showBackendErrorMessages: true,
                        showOptions: true,
                        hidePreview: true,
                        hideSampleData: false,
                        sampleData: [{ partner: "HC00001411", target_oth: "2.5", target_lay: "2.0", target_5s: "4", target_sfi: "1" }],
                        spreadsheetFileName: "Emp_x_KPI_Template.xlsx",
                        i18nModel: this.getView().getModel("i18n"),
                        skipMandatoryFieldCheck: true
                    },
                });

            this.spreadsheetUpload.attachCheckBeforeRead(function (oEvent) {
                debugger;
                const sheetData = oEvent.getParameter("sheetData");
                let errorArray = [];
                let partnerOk = false;
                let target_othOk = false;
                let target_layOk = false;
                for (const [index, row] of sheetData.entries()) {
                    for (const key in row) {
                        if (key === "Business Partner Number[partner]") {
                            partnerOk = true;
                        }
                        if (key === "Audits / Month[target_oth]") {
                            target_othOk = true;
                        }
                        if (key === "Layered Evaluation / Month[target_lay]") {
                            target_layOk = true;
                        }
                    }

                    if (partnerOk === false) {
                        const error = {
                            title: "Business Partner Number is initial",
                            row: index + 2,
                            group: true,
                            ui5type: "Error"
                        };
                        errorArray.push(error);
                    }

                    if (target_othOk === false) {
                        const error = {
                            title: "Audits / Month is initial",
                            row: index + 2,
                            group: true,
                            ui5type: "Error"
                        };
                        errorArray.push(error);
                    }

                    if (target_layOk === false) {
                        const error = {
                            title: "Layered Evaluation / Month is initial",
                            row: index + 2,
                            group: true,
                            ui5type: "Error"
                        };
                        errorArray.push(error);
                    }
                }

                oEvent.getSource().addArrayToMessages(errorArray);
            }, this);

            this.spreadsheetUpload.attachChangeBeforeCreate(function (oEvent) {
                let payload = oEvent.getParameter("payload");
                oEvent.getSource().setPayload(payload);
            }, this);

            this.spreadsheetUpload.attachRequestCompleted(function (oEvent) {
                const success = oEvent.getParameter("success");
                if (success) {
                    console.log("Request Completed");
                } else {
                    console.log("Request Failed");
                }
            }, this);

            this.spreadsheetUpload.openSpreadsheetUploadDialog();
            this.getView().setBusy(false);
        }
    };
});
```

### Manifest

```json
{
  "_version": "1.48.0",
  "sap.app": {
    "id": "configemployeekpi.zehsamcfgemp",
    "type": "application",
    "i18n": "i18n/i18n.properties",
    "applicationVersion": {
      "version": "0.0.1"
    },
    "title": "{{appTitle}}",
    "description": "{{appDescription}}",
    "resources": "resources.json",
    "sourceTemplate": {
      "id": "@sap/generator-fiori:lrop",
      "version": "1.10.5",
      "toolsId": "f8838881-294c-4bbc-80e5-b861178592ea"
    },
    "dataSources": {
      "mainService": {
        "uri": "/sap/opu/odata/sap/ZUI_CONFIG_EMPLOYEE/",
        "type": "OData",
        "settings": {
          "annotations": [
            "ZUI_CONFIG_EMPLOYEE_VAN",
            "annotation"
          ],
          "localUri": "localService/metadata.xml",
          "odataVersion": "2.0"
        }
      },
      "ZUI_CONFIG_EMPLOYEE_VAN": {
        "uri": "/sap/opu/odata/IWFND/CATALOGSERVICE;v=2/Annotations(TechnicalName='ZUI_CONFIG_EMPLOYEE_VAN',Version='0001')/$value/",
        "type": "ODataAnnotation",
        "settings": {
          "localUri": "localService/ZUI_CONFIG_EMPLOYEE_VAN.xml"
        }
      },
      "annotation": {
        "type": "ODataAnnotation",
        "uri": "annotations/annotation.xml",
        "settings": {
          "localUri": "annotations/annotation.xml"
        }
      }
    },
    "crossNavigation": {
      "inbounds": {
        "ConfigEmployee-manage": {
          "semanticObject": "ConfigEmployee",
          "action": "manage",
          "title": "{{flpTitle}}",
          "subTitle": "{{flpSubtitle}}",
          "signature": {
            "parameters": {},
            "additionalParameters": "allowed"
          }
        }
      }
    }
  },
  "sap.ui": {
    "technology": "UI5",
    "icons": {
      "icon": "",
      "favIcon": "",
      "phone": "",
      "phone@2": "",
      "tablet": "",
      "tablet@2": ""
    },
    "deviceTypes": {
      "desktop": true,
      "tablet": true,
      "phone": true
    }
  },
  "sap.ui5": {
    "flexEnabled": true,
    "componentUsages": {
      "spreadsheetImporter": {
        "name": "cc.spreadsheetimporter.v0_33_0"
      }
    },
    "resourceRoots": {
      "cc.spreadsheetimporter.v0_33_0": "./thirdparty/customControl/spreadsheetImporter/v0_33_0"
    },
    "dependencies": {
      "minUI5Version": "1.108.4",
      "libs": {
        "sap.m": {},
        "sap.ui.core": {},
        "sap.ushell": {},
        "sap.f": {},
        "sap.ui.comp": {},
        "sap.ui.generic.app": {},
        "sap.suite.ui.generic.template": {}
      }
    },
    "contentDensities": {
      "compact": true,
      "cozy": true
    },
    "models": {
      "i18n": {
        "type": "sap.ui.model.resource.ResourceModel",
        "settings": {
          "bundleName": "configemployeekpi.zehsamcfgemp.i18n.i18n"
        }
      },
      "": {
        "dataSource": "mainService",
        "preload": true,
        "settings": {
          "defaultBindingMode": "TwoWay",
          "defaultCountMode": "Inline",
          "refreshAfterChange": false,
          "metadataUrlParams": {
            "sap-value-list": "none"
          }
        }
      },
      "@i18n": {
        "type": "sap.ui.model.resource.ResourceModel",
        "uri": "i18n/i18n.properties"
      }
    },
    "resources": {
      "css": []
    },
    "routing": {
      "config": {},
      "routes": [],
      "targets": {}
    },
    "extends": {
      "extensions": {
        "sap.ui.controllerExtensions": {
          "sap.suite.ui.generic.template.ListReport.view.ListReport": {
            "controllerName": "configemployeekpi.zehsamcfgemp.ext.controller.ListReportExt",
            "sap.ui.generic.app": {
              "ConfigEmployee": {
                "EntitySet": "ConfigEmployee",
                "Actions": {
                  "spreadsheetUploadButton": {
                    "id": "spreadsheetUploadButtonButton",
                    "text": "Upload",
                    "press": "openSpreadsheetUploadDialog",
                    "requiresSelection": false
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "sap.ui.generic.app": {
    "_version": "1.3.0",
    "settings": {
      "forceGlobalRefresh": false,
      "objectPageHeaderType": "Dynamic",
      "considerAnalyticalParameters": true,
      "showDraftToggle": false
    },
    "pages": {
      "ListReport|ConfigEmployee": {
        "entitySet": "ConfigEmployee",
        "component": {
          "name": "sap.suite.ui.generic.template.ListReport",
          "list": true,
          "settings": {
            "condensedTableLayout": true,
            "smartVariantManagement": true,
            "enableTableFilterInPageVariant": true,
            "filterSettings": {
              "dateSettings": {
                "useDateRange": true
              }
            },
            "dataLoadSettings": {
              "loadDataOnAppLaunch": "always"
            }
          }
        },
        "pages": {
          "ObjectPage|ConfigEmployee": {
            "entitySet": "ConfigEmployee",
            "defaultLayoutTypeIfExternalNavigation": "MidColumnFullScreen",
            "component": {
              "name": "sap.suite.ui.generic.template.ObjectPage"
            }
          }
        }
      }
    }
  },
  "sap.fiori": {
    "registrationIds": [],
    "archeType": "transactional"
  }
}
```

**Comment by marianfoo** [comment]
Hm, did not see an obvious error.
Does it work when you open it directly without launchpad like:
https://ehsdev.lce.arcelormittal.com:44300/sap/bc/ui5_ui5/sap/ZEHSAM_CFGEMP/index.html

**Comment by leaguiar85** [comment]
Hi Marian,

Yes, this way the application works very well! Thanks!
![image](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/54242167/844a3467-8a18-43ec-91db-d0ab5b57d3cf)

Clicking on Upload, open the fragment
![image](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/54242167/37ac8456-2e6c-43a3-b1df-8c4be3419442)

What do you suggest to work properly in Launchpad? Create a new Tile with a different config? This is my actual Tile 
![image](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/54242167/83516c8e-cd55-4237-a762-9eb801672520)

Thank you!

**Comment by marianfoo** [comment]
> Regarding "With this request i would expect to request Component-preload.js instead of Component.js"
I'm not seeing Component-preload.js in BSP application

No worries, it is deployed, just a bit hidden in SE80. 
It is under those cryptic named files: 
![image](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/13335743/04720fe0-ae36-4afc-816b-bd854d94bd61)

**Comment by leaguiar85** [comment]
Thanks Marian for your help!
I let you know if the application will work properly after the weekend :-)
If not, I will create a new tile with the direct URL without the launchpad.

**Comment by marianfoo** [comment]
need any more help?

**Comment by marianfoo** [comment]
seems issue is solved

**Comment by leaguiar85** [comment]
Hi Marian,

Apologies for the delay, the problem has been solved. It was something in the cache on the backend. I cleared the metadata in /IWFND/MAINT_SERVICE and SAP Gateway Client, and it´s working perfectly inside Launchpad. Thank you so much!

**Comment by marianfoo** [comment]
Happy that it works :)
