### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Manigajula** [spreadsheetimporter/ui5-cc-spreadsheetimporter#542]
### OData Version

OData V2

### Draft

Yes

### Scenario

Fiori Elements

### Environment

BAS

### UI5 Spreadsheet Component

latest

### What happened?

npm install ui5-cc-spreadsheetimporter failed 
![Capture](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/73901416/21b68f74-837c-4fdd-8fae-45ed836109aa)

### Relevant log output

```shell
0 verbose cli /local/asdf-inst-inbox-runtime/installs/nodejs/18.14.2/bin/node /home/user/.asdf-inst/installs/nodejs/18.14.2/bin/npm
1 info using npm@9.5.0
2 info using node@v18.14.2
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/local/asdf-inst-inbox-runtime/installs/nodejs/18.14.2/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/user/projects/ui5-cc-spreadsheetimporter/.npmrc Completed in 1ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/home/user/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/home/user/.node_modules_global/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 6ms
17 timing npm:load:configload Completed in 6ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install
21 verbose argv "install"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 2ms
24 timing npm:load:display Completed in 2ms
25 verbose logfile logs-max:10 dir:/home/user/.npm/_logs/2024-04-24T12_52_59_548Z-
26 verbose logfile /home/user/.npm/_logs/2024-04-24T12_52_59_548Z-debug-0.log
27 timing npm:load:logFile Completed in 3ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 13ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 8 files
33 timing arborist:ctor Completed in 0ms
34 timing idealTree:init Completed in 13ms
35 timing idealTree:userRequests Completed in 0ms
36 silly idealTree buildDeps
37 silly fetch manifest @babel/eslint-parser@7.24.1
38 silly logfile done cleaning log files
39 http fetch GET 200 https://registry.npmjs.org/@babel%2feslint-parser 91ms (cache miss)
40 silly fetch manifest @babel/core@^7.11.0
41 http fetch GET 200 https://registry.npmjs.org/@babel%2fcore 98ms (cache miss)
42 silly fetch manifest eslint@9.0.0
43 http fetch GET 200 https://registry.npmjs.org/eslint 49ms (cache revalidated)
44 silly fetch manifest eslint@^7.5.0 || ^8.0.0
45 timing idealTree Completed in 297ms
46 timing command:install Completed in 302ms
47 verbose stack Error: unable to resolve dependency tree
47 verbose stack     at [failPeerConflict] (/local/asdf-inst-inbox-runtime/installs/nodejs/18.14.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1381:25)
47 verbose stack     at [loadPeerSet] (/local/asdf-inst-inbox-runtime/installs/nodejs/18.14.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1347:34)
47 verbose stack     at async [buildDepStep] (/local/asdf-inst-inbox-runtime/installs/nodejs/18.14.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:929:11)
47 verbose stack     at async Arborist.buildIdealTree (/local/asdf-inst-inbox-runtime/installs/nodejs/18.14.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
47 verbose stack     at async Promise.all (index 1)
47 verbose stack     at async Arborist.reify (/local/asdf-inst-inbox-runtime/installs/nodejs/18.14.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
47 verbose stack     at async Install.exec (/local/asdf-inst-inbox-runtime/installs/nodejs/18.14.2/lib/node_modules/npm/lib/commands/install.js:146:5)
47 verbose stack     at async module.exports (/local/asdf-inst-inbox-runtime/installs/nodejs/18.14.2/lib/node_modules/npm/lib/cli.js:134:5)
48 verbose cwd /home/user/projects/ui5-cc-spreadsheetimporter
49 verbose Linux 6.1.77-gardenlinux-cloud-amd64
50 verbose node v18.14.2
51 verbose npm  v9.5.0
52 error code ERESOLVE
53 error ERESOLVE unable to resolve dependency tree
54 error
55 error While resolving: [1mui5-spreadsheetimporter[22m@[1m0.0.0[22m
55 error Found: [1meslint[22m@[1m9.0.0[22m[2m[22m
55 error [2mnode_modules/eslint[22m
55 error   [33mdev[39m [1meslint[22m@"[1m9.0.0[22m" from the root project
55 error
55 error Could not resolve dependency:
55 error [35mpeer[39m [1meslint[22m@"[1m^7.5.0 || ^8.0.0[22m" from [1m@babel/eslint-parser[22m@[1m7.24.1[22m[2m[22m
55 error [2mnode_modules/@babel/eslint-parser[22m
55 error   [33mdev[39m [1m@babel/eslint-parser[22m@"[1m7.24.1[22m" from the root project
55 error
55 error Fix the upstream dependency conflict, or retry
55 error this command with --force or --legacy-peer-deps
55 error to accept an incorrect (and potentially broken) dependency resolution.
56 error
56 error
56 error For a full report see:
56 error /home/user/.npm/_logs/2024-04-24T12_52_59_548Z-eresolve-report.txt
57 verbose exit 1
58 timing npm Completed in 346ms
59 verbose unfinished npm timer reify 1713963179588
60 verbose unfinished npm timer reify:loadTrees 1713963179590
61 verbose unfinished npm timer idealTree:buildDeps 1713963179604
62 verbose unfinished npm timer idealTree:#root 1713963179605
63 verbose code 1
64 error A complete log of this run can be found in:
64 error     /home/user/.npm/_logs/2024-04-24T12_52_59_548Z-debug-0.log
```

### Spreadsheet Component Init

```js
All
```

### Manifest

```json
yet to code
```

**Comment by marianfoo** [comment]
Hi @Manigajula ,
I tested the url 
https://cdn.sheetjs.com/xlsx-0.20.2/package/dist/xlsx.full.min.js
And it Is available.
High likely your corporate network is blocking the request.
Please speak with your administrator.
