### ISSUE TITLE
[Bug]: unable to load script spreadsheetimporter error in BAS with UI5 version 1.120.13

### ISSUE THREAD

**Issue by imran612** [spreadsheetimporter/ui5-cc-spreadsheetimporter#570]
### OData Version

OData V4

### Draft

Yes

### Scenario

Fiori Element

### Environment

BAS

### UI5 Spreadsheet Component

1.0.0

### What happened?

I am trying to install UI5 spreadsheet component in BAS, followed steps mentioned in the Getting Started guide. In custom button creation of component is failing with error: failed to load 'cc/spreadsheetimporter/v1_0_0/Component.js' from sesmassuploadapp.sesappwithexcel/webapp/thirdparty/customcontrol/spreadsheetimporter/v1_0_0/Component.js: 404 not found.

Please see the attached document for details steps and screenshots.
[Excel upload configurations steps.docx](https://github.com/user-attachments/files/15742187/Excel.upload.configurations.steps.docx)

### Relevant log output

<details>

```shell
fetch-dbg.js:209 
        
        
       GET https://port4004-workspaces-ws-v9gxb.eu12.int.applicationstudio.cloud.sap/sesmassuploadapp.sesappwithexcel/webapp/thirdparty/customcontrol/spreadsheetimporter/v1_0_0/manifest.json?sap-language=EN 404 (Not Found)
(anonymous) @ fetch-dbg.js:209
n @ fetch-dbg.js:147
t @ mixedFetch-dbg.js:55
i.loadResource @ LoaderExtensions-dbg.js:320
_.load @ Manifest-dbg.js:816
V @ Component-dbg.js:3103
z @ Component-dbg.js:2739
j.create @ Component-dbg.js:2455
n @ Component-dbg.js:1507
b.runWithOwner @ ManagedObject-dbg.js:1213
j.runAsOwner @ Component-dbg.js:762
j._createComponent @ Component-dbg.js:1518
j.createComponent @ Component-dbg.js:1338
Excelupload @ Excelupload.js?eval:11
eval @ FPMHelper.ts:48
(anonymous) @ ui5loader-dbg.js:2107
setTimeout (async)
s @ ui5loader-dbg.js:59
(anonymous) @ ui5loader-dbg.js:2106
Oe @ ui5loader-dbg.js:1858
r @ ui5loader-dbg.js:2099
eval @ FPMHelper.ts:45
actionWrapper @ FPMHelper.ts:15
y @ ExpressionParser-dbg.js:412
(anonymous) @ ExpressionParser-dbg.js:735
l @ ExpressionParser-dbg.js:915
l.getExternalValue @ CompositeBinding-dbg.js:316
u @ EventHandlerResolver-dbg.js:349
eval @ EventHandlerResolver-dbg.js:173
r.fireEvent @ EventProvider-dbg.js:241
y.fireEvent @ Element-dbg.js:683
(anonymous) @ ManagedObjectMetadata-dbg.js:826
S.ontap @ library-preload.js?eval:206
y._handleEvent @ Element-dbg.js:352
N._handleEvent @ UIArea-dbg.js:1054
dispatch @ jquery-dbg.js:5430
c @ jquery-mobile-custom-dbg.js:1907
d @ jquery-mobile-custom-dbg.js:2030
dispatch @ jquery-dbg.js:5430
y.handle @ jquery-dbg.js:5234
trigger @ jquery-dbg.js:8823
(anonymous) @ jquery-dbg.js:8901
each @ jquery-dbg.js:385
each @ jquery-dbg.js:207
trigger @ jquery-dbg.js:8900
j @ jquery-mobile-custom-dbg.js:1455
L @ jquery-mobile-custom-dbg.js:1465
dispatch @ jquery-dbg.js:5430
y.handle @ jquery-dbg.js:5234
ui5loader-dbg.js:1463 
        
        
       GET https://port4004-workspaces-ws-v9gxb.eu12.int.applicationstudio.cloud.sap/sesmassuploadapp.sesappwithexcel/webapp/thirdparty/customcontrol/spreadsheetimporter/v1_0_0/Component-preload.js net::ERR_ABORTED 404 (Not Found)
Ae @ ui5loader-dbg.js:1463
qe @ ui5loader-dbg.js:1681
Be @ ui5loader-dbg.js:2346
T @ Component-dbg.js:3232
(anonymous) @ Component-dbg.js:3449
Promise.then (async)
V @ Component-dbg.js:3440
z @ Component-dbg.js:2739
j.create @ Component-dbg.js:2455
n @ Component-dbg.js:1507
b.runWithOwner @ ManagedObject-dbg.js:1213
j.runAsOwner @ Component-dbg.js:762
j._createComponent @ Component-dbg.js:1518
j.createComponent @ Component-dbg.js:1338
Excelupload @ Excelupload.js?eval:11
eval @ FPMHelper.ts:48
(anonymous) @ ui5loader-dbg.js:2107
setTimeout (async)
s @ ui5loader-dbg.js:59
(anonymous) @ ui5loader-dbg.js:2106
Oe @ ui5loader-dbg.js:1858
r @ ui5loader-dbg.js:2099
eval @ FPMHelper.ts:45
actionWrapper @ FPMHelper.ts:15
y @ ExpressionParser-dbg.js:412
(anonymous) @ ExpressionParser-dbg.js:735
l @ ExpressionParser-dbg.js:915
l.getExternalValue @ CompositeBinding-dbg.js:316
u @ EventHandlerResolver-dbg.js:349
eval @ EventHandlerResolver-dbg.js:173
r.fireEvent @ EventProvider-dbg.js:241
y.fireEvent @ Element-dbg.js:683
(anonymous) @ ManagedObjectMetadata-dbg.js:826
S.ontap @ library-preload.js?eval:206
y._handleEvent @ Element-dbg.js:352
N._handleEvent @ UIArea-dbg.js:1054
dispatch @ jquery-dbg.js:5430
c @ jquery-mobile-custom-dbg.js:1907
d @ jquery-mobile-custom-dbg.js:2030
dispatch @ jquery-dbg.js:5430
y.handle @ jquery-dbg.js:5234
trigger @ jquery-dbg.js:8823
(anonymous) @ jquery-dbg.js:8901
each @ jquery-dbg.js:385
each @ jquery-dbg.js:207
trigger @ jquery-dbg.js:8900
j @ jquery-mobile-custom-dbg.js:1455
L @ jquery-mobile-custom-dbg.js:1465
dispatch @ jquery-dbg.js:5430
y.handle @ jquery-dbg.js:5234
launchpadPage.html#sesmassuploadappsesappwithexce-display&/SESMainHeader(ID=8aae3bfa-a7bb-4883-b66d-344c8d62bd4b,IsActiveEntity=false)?layout=TwoColumnsMidExpanded:1 Refused to execute script from 'https://port4004-workspaces-ws-v9gxb.eu12.int.applicationstudio.cloud.sap/sesmassuploadapp.sesappwithexcel/webapp/thirdparty/customcontrol/spreadsheetimporter/v1_0_0/Component-preload.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
ui5loader-dbg.js:1463 
        
        
       GET https://port4004-workspaces-ws-v9gxb.eu12.int.applicationstudio.cloud.sap/sesmassuploadapp.sesappwithexcel/webapp/thirdparty/customcontrol/spreadsheetimporter/v1_0_0/Component-preload.js net::ERR_ABORTED 404 (Not Found)
Ae @ ui5loader-dbg.js:1463
i @ ui5loader-dbg.js:1448
error (async)
Ae @ ui5loader-dbg.js:1461
qe @ ui5loader-dbg.js:1681
Be @ ui5loader-dbg.js:2346
T @ Component-dbg.js:3232
(anonymous) @ Component-dbg.js:3449
Promise.then (async)
V @ Component-dbg.js:3440
z @ Component-dbg.js:2739
j.create @ Component-dbg.js:2455
n @ Component-dbg.js:1507
b.runWithOwner @ ManagedObject-dbg.js:1213
j.runAsOwner @ Component-dbg.js:762
j._createComponent @ Component-dbg.js:1518
j.createComponent @ Component-dbg.js:1338
Excelupload @ Excelupload.js?eval:11
eval @ FPMHelper.ts:48
(anonymous) @ ui5loader-dbg.js:2107
setTimeout (async)
s @ ui5loader-dbg.js:59
(anonymous) @ ui5loader-dbg.js:2106
Oe @ ui5loader-dbg.js:1858
r @ ui5loader-dbg.js:2099
eval @ FPMHelper.ts:45
actionWrapper @ FPMHelper.ts:15
y @ ExpressionParser-dbg.js:412
(anonymous) @ ExpressionParser-dbg.js:735
l @ ExpressionParser-dbg.js:915
l.getExternalValue @ CompositeBinding-dbg.js:316
u @ EventHandlerResolver-dbg.js:349
eval @ EventHandlerResolver-dbg.js:173
r.fireEvent @ EventProvider-dbg.js:241
y.fireEvent @ Element-dbg.js:683
(anonymous) @ ManagedObjectMetadata-dbg.js:826
S.ontap @ library-preload.js?eval:206
y._handleEvent @ Element-dbg.js:352
N._handleEvent @ UIArea-dbg.js:1054
dispatch @ jquery-dbg.js:5430
c @ jquery-mobile-custom-dbg.js:1907
d @ jquery-mobile-custom-dbg.js:2030
dispatch @ jquery-dbg.js:5430
y.handle @ jquery-dbg.js:5234
trigger @ jquery-dbg.js:8823
(anonymous) @ jquery-dbg.js:8901
each @ jquery-dbg.js:385
each @ jquery-dbg.js:207
trigger @ jquery-dbg.js:8900
j @ jquery-mobile-custom-dbg.js:1455
L @ jquery-mobile-custom-dbg.js:1465
dispatch @ jquery-dbg.js:5430
y.handle @ jquery-dbg.js:5234
launchpadPage.html#sesmassuploadappsesappwithexce-display&/SESMainHeader(ID=8aae3bfa-a7bb-4883-b66d-344c8d62bd4b,IsActiveEntity=false)?layout=TwoColumnsMidExpanded:1 Refused to execute script from 'https://port4004-workspaces-ws-v9gxb.eu12.int.applicationstudio.cloud.sap/sesmassuploadapp.sesappwithexcel/webapp/thirdparty/customcontrol/spreadsheetimporter/v1_0_0/Component-preload.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
Log-dbg.js:499 2024-06-07 11:07:14.010300 failed to load JavaScript resource: cc/spreadsheetimporter/v1_0_0/Component-preload.js -  sap.ui.ModuleSystem
g @ Log-dbg.js:499
t.error @ Log-dbg.js:249
L.error @ Log-dbg.js:685
i @ ui5loader-dbg.js:1452
error (async)
Ae @ ui5loader-dbg.js:1461
i @ ui5loader-dbg.js:1448
error (async)
Ae @ ui5loader-dbg.js:1461
qe @ ui5loader-dbg.js:1681
Be @ ui5loader-dbg.js:2346
T @ Component-dbg.js:3232
(anonymous) @ Component-dbg.js:3449
Promise.then (async)
V @ Component-dbg.js:3440
z @ Component-dbg.js:2739
j.create @ Component-dbg.js:2455
n @ Component-dbg.js:1507
b.runWithOwner @ ManagedObject-dbg.js:1213
j.runAsOwner @ Component-dbg.js:762
j._createComponent @ Component-dbg.js:1518
j.createComponent @ Component-dbg.js:1338
Excelupload @ Excelupload.js?eval:11
eval @ FPMHelper.ts:48
(anonymous) @ ui5loader-dbg.js:2107
setTimeout (async)
s @ ui5loader-dbg.js:59
(anonymous) @ ui5loader-dbg.js:2106
Oe @ ui5loader-dbg.js:1858
r @ ui5loader-dbg.js:2099
eval @ FPMHelper.ts:45
actionWrapper @ FPMHelper.ts:15
y @ ExpressionParser-dbg.js:412
(anonymous) @ ExpressionParser-dbg.js:735
l @ ExpressionParser-dbg.js:915
l.getExternalValue @ CompositeBinding-dbg.js:316
u @ EventHandlerResolver-dbg.js:349
eval @ EventHandlerResolver-dbg.js:173
r.fireEvent @ EventProvider-dbg.js:241
y.fireEvent @ Element-dbg.js:683
(anonymous) @ ManagedObjectMetadata-dbg.js:826
S.ontap @ library-preload.js?eval:206
y._handleEvent @ Element-dbg.js:352
N._handleEvent @ UIArea-dbg.js:1054
dispatch @ jquery-dbg.js:5430
c @ jquery-mobile-custom-dbg.js:1907
d @ jquery-mobile-custom-dbg.js:2030
dispatch @ jquery-dbg.js:5430
y.handle @ jquery-dbg.js:5234
trigger @ jquery-dbg.js:8823
(anonymous) @ jquery-dbg.js:8901
each @ jquery-dbg.js:385
each @ jquery-dbg.js:207
trigger @ jquery-dbg.js:8900
j @ jquery-mobile-custom-dbg.js:1455
L @ jquery-mobile-custom-dbg.js:1465
dispatch @ jquery-dbg.js:5430
y.handle @ jquery-dbg.js:5234
ui5loader-dbg.js:1392 
        
        
       GET https://port4004-workspaces-ws-v9gxb.eu12.int.applicationstudio.cloud.sap/sesmassuploadapp.sesappwithexcel/webapp/thirdparty/customcontrol/spreadsheetimporter/v1_0_0/Component.js 404 (Not Found)
je @ ui5loader-dbg.js:1392
qe @ ui5loader-dbg.js:1650
Oe @ ui5loader-dbg.js:1843
r @ ui5loader-dbg.js:2099
(anonymous) @ Component-dbg.js:3632
(anonymous) @ Component-dbg.js:3630
Promise.then (async)
V @ Component-dbg.js:3625
z @ Component-dbg.js:2739
j.create @ Component-dbg.js:2455
n @ Component-dbg.js:1507
b.runWithOwner @ ManagedObject-dbg.js:1213
j.runAsOwner @ Component-dbg.js:762
j._createComponent @ Component-dbg.js:1518
j.createComponent @ Component-dbg.js:1338
Excelupload @ Excelupload.js?eval:11
eval @ FPMHelper.ts:48
(anonymous) @ ui5loader-dbg.js:2107
setTimeout (async)
s @ ui5loader-dbg.js:59
(anonymous) @ ui5loader-dbg.js:2106
Oe @ ui5loader-dbg.js:1858
r @ ui5loader-dbg.js:2099
eval @ FPMHelper.ts:45
actionWrapper @ FPMHelper.ts:15
y @ ExpressionParser-dbg.js:412
(anonymous) @ ExpressionParser-dbg.js:735
l @ ExpressionParser-dbg.js:915
l.getExternalValue @ CompositeBinding-dbg.js:316
u @ EventHandlerResolver-dbg.js:349
eval @ EventHandlerResolver-dbg.js:173
r.fireEvent @ EventProvider-dbg.js:241
y.fireEvent @ Element-dbg.js:683
(anonymous) @ ManagedObjectMetadata-dbg.js:826
S.ontap @ library-preload.js?eval:206
y._handleEvent @ Element-dbg.js:352
N._handleEvent @ UIArea-dbg.js:1054
dispatch @ jquery-dbg.js:5430
c @ jquery-mobile-custom-dbg.js:1907
d @ jquery-mobile-custom-dbg.js:2030
dispatch @ jquery-dbg.js:5430
y.handle @ jquery-dbg.js:5234
trigger @ jquery-dbg.js:8823
(anonymous) @ jquery-dbg.js:8901
each @ jquery-dbg.js:385
each @ jquery-dbg.js:207
trigger @ jquery-dbg.js:8900
j @ jquery-mobile-custom-dbg.js:1455
L @ jquery-mobile-custom-dbg.js:1465
dispatch @ jquery-dbg.js:5430
y.handle @ jquery-dbg.js:5234
ui5loader-dbg.js:1156 Uncaught (in promise) ModuleError: failed to load 'cc/spreadsheetimporter/v1_0_0/Component.js' from sesmassuploadapp.sesappwithexcel/webapp/thirdparty/customcontrol/spreadsheetimporter/v1_0_0/Component.js: 404
    at we (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:6645)
    at ge.failWith (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:4709)
    at qe (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:13312)
    at Oe (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:15314)
    at Object.r [as require] (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:18696)
    at https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:446:36487
    at new Promise (<anonymous>)
    at https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:446:36454
Caused by: XHRLoadError: 404
    at n (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:9251)
    at XMLHttpRequest.<anonymous> (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:9504)
    at je (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:9596)
    at qe (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:13287)
    at Oe (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:15314)
    at Object.r [as require] (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:18696)
    at https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:446:36487
    at new Promise (<anonymous>)
    at https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:446:36454Caused by: XHRLoadError: 404
    at n (ui5loader-dbg.js:1369:12)
    at XMLHttpRequest.<anonymous> (ui5loader-dbg.js:1382:21)
    at je (ui5loader-dbg.js:1392:8)
    at qe (ui5loader-dbg.js:1650:5)
    at Oe (ui5loader-dbg.js:1843:20)
    at Object.r [as require] (ui5loader-dbg.js:2099:4)
    at Component-dbg.js:3632:13
    at new Promise (<anonymous>)
    at Component-dbg.js:3630:12
we @ ui5loader-dbg.js:1156
failWith @ ui5loader-dbg.js:934
qe @ ui5loader-dbg.js:1655
Oe @ ui5loader-dbg.js:1843
r @ ui5loader-dbg.js:2099
(anonymous) @ Component-dbg.js:3632
(anonymous) @ Component-dbg.js:3630
Promise.then (async)
j.registerForDestroy @ Component-dbg.js:3985
j.createComponent @ Component-dbg.js:1340
Excelupload @ Excelupload.js?eval:11
eval @ FPMHelper.ts:48
(anonymous) @ ui5loader-dbg.js:2107
setTimeout (async)
s @ ui5loader-dbg.js:59
(anonymous) @ ui5loader-dbg.js:2106
Oe @ ui5loader-dbg.js:1858
r @ ui5loader-dbg.js:2099
eval @ FPMHelper.ts:45
actionWrapper @ FPMHelper.ts:15
y @ ExpressionParser-dbg.js:412
(anonymous) @ ExpressionParser-dbg.js:735
l @ ExpressionParser-dbg.js:915
l.getExternalValue @ CompositeBinding-dbg.js:316
u @ EventHandlerResolver-dbg.js:349
eval @ EventHandlerResolver-dbg.js:173
r.fireEvent @ EventProvider-dbg.js:241
y.fireEvent @ Element-dbg.js:683
(anonymous) @ ManagedObjectMetadata-dbg.js:826
S.ontap @ library-preload.js?eval:206
y._handleEvent @ Element-dbg.js:352
N._handleEvent @ UIArea-dbg.js:1054
dispatch @ jquery-dbg.js:5430
c @ jquery-mobile-custom-dbg.js:1907
d @ jquery-mobile-custom-dbg.js:2030
dispatch @ jquery-dbg.js:5430
y.handle @ jquery-dbg.js:5234
trigger @ jquery-dbg.js:8823
(anonymous) @ jquery-dbg.js:8901
each @ jquery-dbg.js:385
each @ jquery-dbg.js:207
trigger @ jquery-dbg.js:8900
j @ jquery-mobile-custom-dbg.js:1455
L @ jquery-mobile-custom-dbg.js:1465
dispatch @ jquery-dbg.js:5430
y.handle @ jquery-dbg.js:5234
ui5loader-dbg.js:1156 Uncaught (in promise) ModuleError: failed to load 'cc/spreadsheetimporter/v1_0_0/Component.js' from sesmassuploadapp.sesappwithexcel/webapp/thirdparty/customcontrol/spreadsheetimporter/v1_0_0/Component.js: 404
    at we (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:6645)
    at ge.failWith (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:4709)
    at qe (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:13312)
    at Oe (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:15314)
    at Object.r [as require] (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:18696)
    at https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:446:36487
    at new Promise (<anonymous>)
    at https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:446:36454
Caused by: XHRLoadError: 404
    at n (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:9251)
    at XMLHttpRequest.<anonymous> (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:9504)
    at je (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:9596)
    at qe (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:13287)
    at Oe (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:15314)
    at Object.r [as require] (https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:10:18696)
    at https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:446:36487
    at new Promise (<anonymous>)
    at https://ui5.sap.com/1.120.13/resources/sap-ui-core.js:446:36454Caused by: XHRLoadError: 404
    at n (ui5loader-dbg.js:1369:12)
    at XMLHttpRequest.<anonymous> (ui5loader-dbg.js:1382:21)
    at je (ui5loader-dbg.js:1392:8)
    at qe (ui5loader-dbg.js:1650:5)
    at Oe (ui5loader-dbg.js:1843:20)
    at Object.r [as require] (ui5loader-dbg.js:2099:4)
    at Component-dbg.js:3632:13
    at new Promise (<anonymous>)
    at Component-dbg.js:3630:12
we @ ui5loader-dbg.js:1156
failWith @ ui5loader-dbg.js:934
qe @ ui5loader-dbg.js:1655
Oe @ ui5loader-dbg.js:1843
r @ ui5loader-dbg.js:2099
(anonymous) @ Component-dbg.js:3632
(anonymous) @ Component-dbg.js:3630
setTimeout (async)
s @ ui5loader-dbg.js:59
(anonymous) @ ui5loader-dbg.js:2116
Oe @ ui5loader-dbg.js:1856
r @ ui5loader-dbg.js:2099
(anonymous) @ Component-dbg.js:3632
(anonymous) @ Component-dbg.js:3630
Promise.then (async)
V @ Component-dbg.js:3625
z @ Component-dbg.js:2739
j.create @ Component-dbg.js:2455
n @ Component-dbg.js:1507
b.runWithOwner @ ManagedObject-dbg.js:1213
j.runAsOwner @ Component-dbg.js:762
j._createComponent @ Component-dbg.js:1518
j.createComponent @ Component-dbg.js:1338
Excelupload @ Excelupload.js?eval:11
eval @ FPMHelper.ts:48
(anonymous) @ ui5loader-dbg.js:2107
setTimeout (async)
s @ ui5loader-dbg.js:59
(anonymous) @ ui5loader-dbg.js:2106
Oe @ ui5loader-dbg.js:1858
r @ ui5loader-dbg.js:2099
eval @ FPMHelper.ts:45
actionWrapper @ FPMHelper.ts:15
y @ ExpressionParser-dbg.js:412
(anonymous) @ ExpressionParser-dbg.js:735
l @ ExpressionParser-dbg.js:915
l.getExternalValue @ CompositeBinding-dbg.js:316
u @ EventHandlerResolver-dbg.js:349
eval @ EventHandlerResolver-dbg.js:173
r.fireEvent @ EventProvider-dbg.js:241
y.fireEvent @ Element-dbg.js:683
(anonymous) @ ManagedObjectMetadata-dbg.js:826
S.ontap @ library-preload.js?eval:206
y._handleEvent @ Element-dbg.js:352
N._handleEvent @ UIArea-dbg.js:1054
dispatch @ jquery-dbg.js:5430
c @ jquery-mobile-custom-dbg.js:1907
d @ jquery-mobile-custom-dbg.js:2030
dispatch @ jquery-dbg.js:5430
y.handle @ jquery-dbg.js:5234
trigger @ jquery-dbg.js:8823
(anonymous) @ jquery-dbg.js:8901
each @ jquery-dbg.js:385
each @ jquery-dbg.js:207
trigger @ jquery-dbg.js:8900
j @ jquery-mobile-custom-dbg.js:1455
L @ jquery-mobile-custom-dbg.js:1465
dispatch @ jquery-dbg.js:5430
y.handle @ jquery-dbg.js:5234
```
</details>

### Spreadsheet Component Init

```js
sap.ui.define([
    "sap/m/MessageToast"
], function(MessageToast) {
    'use strict';

    return {
        Excelupload:  async function(oEvent) {
            MessageToast.show("Custom handler invoked.");
            //this._view.setBusyIndicatorDelay(0); 
            //this._view.setBusy(true);
            this.spreadsheetUpload =  await this._view.getController().getAppComponent().createComponent({
                usage: "spreadsheetImporter",
                async: true,
                    componentData: {
                        context: this,
                        debug: true
                    },
                });
            this.spreadsheetUpload.openSpreadsheetUploadDialog();
            //this._view.setBusy(false);
        }
    };
});
```

### Manifest

```json
"componentUsages": {
      "spreadsheetImporter": {
        "name": "cc.spreadsheetimporter.v1_0_0"
      }
    },
    "resourceRoots": {
      "cc.spreadsheetimporter.v1_0_0": "./thirdparty/customcontrol/spreadsheetimporter/v1_0_0"
    },
```

**Comment by marianfoo** [comment]
Please try to start the UI5 App from the index.html and not in the local launchpad

**Comment by imran612** [comment]
Thanks for your response. After running the application from index.html getting the following error (screenshot attached)
![Screenshot 2024-06-10 at 8 40 19 AM](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/4041201/6e8a5d4f-7892-4db4-99ab-47d6b0f6b275)
![Screenshot 2024-06-10 at 8 41 00 AM](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/4041201/66e19010-6084-4a01-9174-1de9ee7c22cc)


ModuleError: failed to load 'cc/spreadsheetimporter/v1_0_0/Component.js' from thirdparty/customcontrol/spreadsheetimporter/v1_0_0/Component.js: script load error

**Comment by imran612** [comment]
Hi Marian, Appreciate if you can provide your input, I need to show excelupload demo to users otherwise there is a strong push to go towards building freestyle Fiori app with custom excel upload functionality. I would like to stick to fiori element with spreadsheetimporter module. Please help. Thank you.

**Comment by imran612** [comment]
Hi Marian, No luck even after changing UI5 version to 1.108. I followed all the steps mentioned in Getting Started section. Again I am using BAS with Productivity Tool dev space for developing full stack application. Appreciate your help!

**Comment by marianfoo** [comment]
Hi, it seems the app wants to load the component from the UI5 CDN, so the resourceRoots from the manifest does not work.
In your index.html you have something like resourceRoots or modulePath.
Try insert this and see if the app tries to load it locally instead of the UI5 CDN:

```json
"cc.spreadsheetimporter.v1_0_0": "./sesmassuploadapp.sesappwithexcel/resources/cc/spreadsheetimporter/v1_0_0/",
```

or maybe 

```json
"cc.spreadsheetimporter.v1_0_0": "./sesmassuploadapp.sesappwithexcel/webapp/resources/cc/spreadsheetimporter/v1_0_0/",
```

**Comment by imran612** [comment]
Thanks for your response Marian. I tried both the options but still component is not loaded. Please screenshot below. What might be changed? I followed standard documentation for setup, does the step got changed in BAS?

![Screenshot 2024-06-13 at 11 49 29 AM](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/4041201/9ea4a437-84db-4f43-aa07-fbb0600a8141)

![Screenshot 2024-06-13 at 11 50 10 AM](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/4041201/68c21043-05d8-477b-8804-52f9023c3b75)

![Screenshot 2024-06-13 at 11 50 21 AM](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/4041201/c9ac3d3e-70e5-4127-b425-989727fc6efb)

**Comment by imran612** [comment]
Hi Marian, Any input? please share your thoughts!

**Comment by sammok83** [comment]
Same issue here. Works from the sample (v0.31.1), but doesn't work with the latest version 1.1.1.
Best way to replicate this is to clone the given sample https://github.com/spreadsheetimporter/sample-full-btp and upgrade v1.1.1 there and you'll see the same error as original poster.

**Comment by imran612** [comment]
> Same issue here. Works from the sample (v0.31.1), but doesn't work with the latest version 1.1.1. Best way to replicate this is to clone the given sample https://github.com/spreadsheetimporter/sample-full-btp and upgrade v1.1.1 there and you'll see the same error as original poster.
> 
> I got pass this by: ![image](https://private-user-images.githubusercontent.com/10509241/341935499-e90663fb-9a76-45f4-a47c-43f4a07efbfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzIyMjIsIm5iZiI6MTcxOTIzMTkyMiwicGF0aCI6Ii8xMDUwOTI0MS8zNDE5MzU0OTktZTkwNjYzZmItOWE3Ni00NWY0LWE0N2MtNDNmNGEwN2VmYmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDEyMjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNzMyNDA0NzNmOTY4MjMyYWQ4YmIwMTViM2Y1MTc3ZDFkNjk5MzllMjc2MDYwN2M4ZWNkMTY3ZDE4ZWI4NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eWkizlRgL5OSchphMOweEcCcuC33dO0im674uaMeMc8)

How can I install lower version of excel importer v0.31.1?

**Comment by imran612** [comment]
How can we install lower version v0.31.1? Please advise.

**Comment by marianfoo** [comment]
Sorry, was not able to reproduce your errors.  
Do you have a sample that does not work?
https://github.com/spreadsheetimporter/sample-full-btp/commit/0ef14905865219f7acd3a357cce34929879098a1
![image](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/13335743/498997c8-eb3d-4d4a-ad9b-6b988c98a378)

**Comment by imran612** [comment]
Thanks Marian. Please review the sourcecode 
https://github.com/imran612/testspreadsheet

Here is the error screenshot
![Screenshot 2024-06-26 at 6 24 49 PM](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/assets/4041201/3dde593e-4369-4a1b-91ae-9c8b485a67a6)

**Comment by imran612** [comment]
> Sorry, was not able to reproduce your errors. Do you have a sample that does not work? [spreadsheetimporter/sample-full-btp@0ef1490](https://github.com/spreadsheetimporter/sample-full-btp/commit/0ef14905865219f7acd3a357cce34929879098a1) ![image](https://private-user-images.githubusercontent.com/13335743/342473978-498997c8-eb3d-4d4a-ad9b-6b988c98a378.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NDQ2MzQsIm5iZiI6MTcxOTQ0NDMzNCwicGF0aCI6Ii8xMzMzNTc0My8zNDI0NzM5NzgtNDk4OTk3YzgtZWIzZC00ZDRhLWFkOWItNmI5ODhjOThhMzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDIzMjUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkOGQ2YTYzNDEwOWQzYmMyMDZlYTRmZmQwMDYyYTQ4ZWFiODc4MDUzNzNiY2M0OTcyYTUzYmVmYjhhOTA3MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3su9pLBtVNDFC1AO3gpyR_DnuoqiBPbLjYpwhhT7vfQ)

Please see the git repo to reproduce the error
https://github.com/imran612/testspreadsheet

**Comment by marianfoo** [comment]
fixed, same steps as in my sample application
might add that to the docs
https://github.com/imran612/testspreadsheet/pull/1

does that help?

**Comment by marianfoo** [comment]
@imran612 did that help? how can i improve the docs?
