### ISSUE TITLE
[Bug]: Found more than one table on Object Page. Please specify table in option 'tableId'

### ISSUE THREAD

**Issue by alimert801** [spreadsheetimporter/ui5-cc-spreadsheetimporter#689]
### OData Version

OData V4

### Draft

Yes

### Scenario

Fiori Elements, List Report

### Environment

BAS

### UI5 Spreadsheet Component

v1.4.3

### What happened?

I am experiencing an issue. I have also checked with other versions, including the last version v1.5.2. All versions that I have checked have this issue. So that I give an example scenario from your sample app ([sample app](https://livedemo.spreadsheet-importer.com/launchpad.html#ordersv4fe-120)). It happens after opening a filter popup that has a value help table inside, like the "Currency" field in the sample app. Until refreshing the page, it keeps showing the below error. I have put screenshots of steps:
![Image](https://github.com/user-attachments/assets/6abef301-0aee-423f-8f89-a9cac410516c)
![Image](https://github.com/user-attachments/assets/6aaf9ae4-180a-4ae8-9e08-39fb74ea8084)

### Relevant log output

```shell
Error: Found more than one table on Object Page.
Please specify table in option 'tableId'
at constructor.e [as getTableObject] (https://livedemo.spreadsheet-importer.com/ui.v4.ordersv4fe/thirdparty/customcontrol/spreadsheetimporter/v1_5_2/Component-preload.js:74:3175)
at t.e [as setContext] (https://livedemo.spreadsheet-importer.com/ui.v4.ordersv4fe/thirdparty/customcontrol/spreadsheetimporter/v1_5_2/Component-preload.js:35:2216)
at t.e [as initialSetup] (https://livedemo.spreadsheet-importer.com/ui.v4.ordersv4fe/thirdparty/customcontrol/spreadsheetimporter/v1_5_2/Component-preload.js:35:1575)
at async t.e [as initializeComponent] (https://livedemo.spreadsheet-importer.com/ui.v4.ordersv4fe/thirdparty/customcontrol/spreadsheetimporter/v1_5_2/Component-preload.js:35:4958)
at async t.e [as openSpreadsheetUploadDialog] (https://livedemo.spreadsheet-importer.com/ui.v4.ordersv4fe/thirdparty/customcontrol/spreadsheetimporter/v1_5_2/Component-preload.js:35:5278)
```

### Spreadsheet Component Init

```js
onUploadData: async function (oEvent, oParam, oContext) {
  this.base.editFlow.getView().setBusyIndicatorDelay(0);
  this.base.editFlow.getView().setBusy(true);
  this.spreadsheetUpload = await this.base.editFlow.getView()
    .getController()
    .getAppComponent()
    .createComponent({
    usage: "spreadsheetImporter",
    async: true,
    componentData: {
      context: this,
      createActiveEntity: true,
      i18nModel: this.base.getModel('i18n')
    },
  });
  this.spreadsheetUpload.attachRequestCompleted(function (event) {
    const success = event.getParameter("success");
    if (success) {
      this.spreadsheetUpload?.spreadsheetUpload?.getSpreadsheetUploadDialog()?.close()
      oContext?.refresh();
    } else {
      console.log("Spreadsheet Upload Request Failed");
    }
  }.bind(this), this);
  this.spreadsheetUpload.openSpreadsheetUploadDialog();
  this.base.editFlow.getView().setBusy(false);
}
```

### Manifest

```json
"componentUsages": {
  "spreadsheetImporter": {
    "url": "/sap/bc/ui5_ui5/sap/z_xup_v1_4_3",
    "name": "cc.spreadsheetimporter.v1_4_3"
  }
},
```

**Comment by marianfoo** [comment]
You can specify the table ID as described in the error dialogue :)

**Comment by alimert801** [comment]
Thanks for your reply. You are right as you said, it is missing in the "Getting Started" section and in the sample app, must be solved in design time so that confusing and could be more helpful to add recommendation for consistency :)
