### ISSUE TITLE
[Bug]: Spreadsheetimporter is not working in Fiori launchpad

### ISSUE THREAD

**Issue by tamilselvanmbp** [spreadsheetimporter/ui5-cc-spreadsheetimporter#695]
### OData Version

OData V4

### Draft

Yes

### Scenario

Fiori Elements, List Report

### Environment

VS Code, FLP on Premise

### UI5 Spreadsheet Component

v1_5_0

### What happened?

I created the custom BSP application ZHR_EMP_USERID and am using spreadsheet importer in it. The OData service is V4.
As per the document, I implemented the central deployment procedure. For UI5 Carrier App, I created the app ZCA_SSUPLOAD.
When I test the app from VS Code, it is working as expected.
After deploying the apps, it is not working in SAP Fiori launchpad and generating the error.

### Relevant log output

```shell
Uncaught (in promise) ModuleError: failed to load 'com/spreadsheetimporter/abapdeploy/Component.js' from ../ui5_ui5/sap/zhr_emp_userid/ZCA_SSUPLOAD/thirdparty/customcontrol/spreadsheetimporter/v1_5_0/Component.js: 404 - NOT FOUND
```

### Spreadsheet Component Init

```js
sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","./model/models"],function(t,e,s){"use strict";return t.extend("com.spreadsheetimporter.abapdeploy.Component",{metadata:{manifest:"json"},init:function(){t.prototype.init.call(this);this.setModel(s+
.createDeviceModel(),"device");this.getRouter().initialize()},getContentDensityClass:function(){if(this.contentDensityClass===undefined){if(document.body.classList.contains("sapUiSizeCozy")||document.body.classList.contains("sapUiSizeCompact")){this.cont+
entDensityClass=""}else if(!e.support.touch){this.contentDensityClass="sapUiSizeCompact"}else{this.contentDensityClass="sapUiSizeCozy"}}return this.contentDensityClass}})});
//# sourceMappingURL=Component.js.map
```

### Manifest

```json
"componentUsages": {
      "spreadsheetImporter": {
        "name": "com.spreadsheetimporter.abapdeploy"
      }
    },
    "resourceRoots": {
      "com.spreadsheetimporter.abapdeploy": "../ZCA_SSUPLOAD/thirdparty/customcontrol/spreadsheetimporter/v1_5_0"
    },
```

**Comment by MARCxGAMBIT** [comment]
Did you update the build command in the package.json?

```json
"scripts": {
  "build": "ui5 build --config=ui5.yaml --all --clean-dest --dest dist"
}
```

Can you confirm that the BSP app contains the thirdparty folder in transaction SE80?

**Comment by marianfoo** [comment]
Hi @tamilselvanmbp 
you said you´re using the central deployment??
If yes, you only use `componentUsages` in your manifest and nothing else.
Try removing `resourceRoots`, deploy and try again.

**Comment by tamilselvanmbp** [comment]
Hi @MARCxGAMBIT,

Yes, I used the below code in the package.json
"build": "ui5 build --config=ui5.yaml --all --clean-dest --dest dist"

Hi @marianfoo ,
When I do not use the rosourceRoots, I am getting the below error.

**ListReportExt-dbg.js:22 Uncaught (in promise) TypeError: this.spreadsheetUpload.openSpreadsheetUploadDialog is not a function
    at e.uploadSpreadSheet (ListReportExt-dbg.js:22:36)**

When I use the below URL as resourceRoots, it is working in Fiori launchpad
"resourceRoots":{
"com.spreadsheetimporter.abapdeploy": "../../../../ui5_ui5/sap/ZCA_SSUPLOAD/thirdparty/customcontrol/spreadsheetimporter/v1_5_0"
}

But the spreadSheetUploader is not working in index.html. The URL as below.
https://<URL of the fiori launchpad>/sap/bc/ui5_ui5/sap/zhr_emp_userid/index.html?sap-client=400

Why it is only in Fiori Launchpad but not in the index.html page?

Regards,
Tamilselvan

**Comment by marianfoo** [comment]
The advantage of the Fioir Launchpad is that the App Index can assign the namespaces. 
So if you used central deployment you dont need `resourceRoots` because App Index will resolve the reference to `"cc.spreadsheetimporter.v1_5_0"`.  
You need `resourceRoots` in your index.html to reference to the path.

Just to be clear, this has nothing to do with my component, but rather with the general use of UI5 components in an on-premise system.

What does the request to the component look like when you remove `resourceRoots` and run it in FLP?

**Comment by tamilselvanmbp** [comment]
Hi @marianfoo ,

As I removed the resourceRoots in manifest, I am getting the below error in the fiori.

Browser console error:

Uncaught (in promise) TypeError: this.spreadsheetUpload.openSpreadsheetUploadDialog is not a function
    at e.uploadSpreadSheet (ListReportExt-dbg.js:22:36)

Regards,
Tamilselvan

**Comment by marianfoo** [comment]
@tamilselvanmbp is this your only error? Please share the complete JS code

**Comment by tamilselvanmbp** [comment]
@marianfoo Yes, this is the only error appearing in the browser console.

**Comment by marianfoo** [comment]
@tamilselvanmbp Please share the complete JS code

**Comment by tamilselvanmbp** [comment]
[Spreadsheet file.zip](https://github.com/user-attachments/files/18737122/Spreadsheet.file.zip)
@marianfoo Please find the attached document.

**Comment by marianfoo** [comment]
in the manifest you need the version of the spreadsheet importer you deployed in your abap system like:  
```json
"componentUsages": {
  "spreadsheetImporter": {
    "name": "cc.spreadsheetimporter.v1_7_2"
  }
}
````

please read the documentation carefully:  
https://docs.spreadsheet-importer.com/pages/GettingStarted/#setup-for-central-deployment

**Comment by marianfoo** [comment]
no response

**Comment by SaswataChandra** [comment]
@tamilselvanmbp Could you please share your final manifest.js, ui5-deploy.yml and package.json file along with the controller where you used this. I'm getting errors in deployment but surprizingly the deployment is happening at the ABAP system. 
If I remove my resourceRoot, it doesn't work in my BAS locals. But @marianfoo  is strongly saying to remove the resourceRoots. 
I'm confused :(
